model:
  class_path: glaucoma_vf.models.dummy_grape_vf_model.DummyVFModel
data:
  class_path: glaucoma_vf.data.grape.datamodule.GRAPEDataModule
  init_args:
    batch_size: 32
trainer:
  callbacks:
    - class_path: glaucoma_vf.callbacks.grape_logger.GRAPELogger